language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

before_scraipt: pip install docker-compose

scraipt:
  - docker-compose run app sh -c "python manage.py test && flake8"