# Generated by Django 3.2.9 on 2021-11-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
